#!/bin/csh -f

set DIR = `pwd`
echo
echo $DIR

#directory of excutable

#run options
echo input file $DIR/in-$1
echo output directory $DIR/out-$1
mpirun -np 4 $DIR/iFluid -d 2 -p 1 4 -i $DIR/in-$1 -o $DIR/out-$1
