#!/bin/bash
#$ -pe mpi 1 
#$ -q nodes.q
#$ -j y
#$ -cwd 

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc
module load intel
module load openmpi-1.8/intel

/act/openmpi-1.8/intel/bin/mpirun -np 1 $DIR/climate -d 3 -p 1 1 1 -i $DIR/in-$prob -o $DIR/out-$prob
