#!/bin/bash 
#$ -pe mpi 64 
#$ -q nodes.q
#$ -j y
#$ -R y
#$ -cwd 

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc

mpirun -np 64 $DIR/climate -d 2 -p 8 8 -i $DIR/in-$prob -o $DIR/out-$prob
