#!/bin/bash 
#$ -pe mpi 8 
#$ -q nodes.q
#$ -j y
#$ -cwd 

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc
module load intel
module load openmpi-1.8/intel

/act/openmpi-1.8/intel/bin/mpirun -np 4 $DIR/climate -d 2 -p 2 2 -i $DIR/in-$prob -o $DIR/out-$prob
