#!/bin/bash
#$ -pe mpi 64 
#$ -q nodes.q
#$ -j y
#$ -R y
#$ -cwd 

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc

mpirun -np 64 $DIR/climate -d 3 -p 4 4 4 -i $DIR/in-$1 -o $DIR/out-$1
