#!/bin/bash 
#$ -pe mpi 16 
#$ -q nodes.q
#$ -j y
#$ -R y
#$ -cwd 

#directory of excutable
DIR=`pwd`
echo $DIR

source /etc/profile.d/modules.sh
source /home/zgao/.bashrc

mpirun -np 16 $DIR/climate -d 2 -p 4 4 -i $DIR/in-$1 -o $DIR/out-$1
